"""Proves the cc-transcript-backed parse path reproduces the legacy parser
byte-for-byte: same messages, same bucket keys, over fixtures and the real
corpus. The legacy ``build_message`` is vendored verbatim here so the guarantee
survives the parser.py rewrite.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

import orjson
import pytest
from cc_transcript import CLAUDE_PROJECTS_DIR, SENTIMENT_SPEC, apply_spec, parse_events_from_bytes

from cc_sentiment.models import AssistantMessage, BucketKey, SessionId, ToolCall, TranscriptMessage, UserMessage
from cc_sentiment.transcripts.adapter import to_messages
from cc_sentiment.transcripts.bucketer import extract_bucket_keys

if TYPE_CHECKING:
    from collections.abc import Iterator

REAL_CORPUS_SAMPLE = 40
FIXTURE_PATH = Path(__file__).parent / "fixtures" / "sample_transcript.jsonl"

# ---- legacy parser, vendored verbatim from the pre-migration parser.py ----

LEGACY_ASSISTANT_TRUNCATION = 1024
LEGACY_EPHEMERAL_ENTRYPOINTS: frozenset[str] = frozenset({"sdk-cli"})

LEGACY_JUNK_RE = re.compile(
    r"<(?:system[_-](?:instruction|reminder)"
    r"|local-command-(?:stdout|caveat)"
    r"|command-(?:name|message|args)"
    r"|task-notification"
    r"|persisted-output"
    r"|output-file)\b"
    r"|Caveat: The messages below were generated by the user while running local commands\."
    r"|\[Request interrupted by user"
    r"|Stop hook feedback:"
    r"|REMAINING_TASKS_ACKNOWLEDGED"
    r"|<<[a-z][a-z0-9-]*>>"
    r"|^Base directory for this skill:"
    r"|(?:###\s+[\w][\w \-]{0,30}\s+){3,}###",
    re.IGNORECASE,
)


def legacy_build_message(data: dict[str, Any]) -> TranscriptMessage | None:
    if data.get("isCompactSummary") or data.get("isVisibleInTranscriptOnly"):
        return None
    if data.get("entrypoint") in LEGACY_EPHEMERAL_ENTRYPOINTS:
        return None
    match data["type"]:
        case "queue-operation":
            return None
        case "user" if data.get("isSidechain"):
            return None
        case "user":
            match data["message"]["content"]:
                case str(raw):
                    content = raw
                case list(blocks) if (
                    parts := [b["text"] for b in blocks if isinstance(b, dict) and b.get("type") == "text"]
                ):
                    content = " ".join(parts)
                case _:
                    return None
            if LEGACY_JUNK_RE.search(content):
                return None
            content = content.strip()
            if not content:
                return None
            return UserMessage(
                content=content,
                timestamp=datetime.fromisoformat(data["timestamp"]),
                session_id=SessionId(data["sessionId"]),
                uuid=data["uuid"],
                tool_calls=(),
                thinking_chars=0,
                cc_version=data.get("version", ""),
            )
        case "assistant" if data["message"]["model"] == "<synthetic>":
            return None
        case "assistant":
            blocks = data["message"]["content"]
            text_blocks = [b["text"] for b in blocks if isinstance(b, dict) and b.get("type") == "text"]
            tool_calls = tuple(
                ToolCall(name=b["name"], file_path=b.get("input", {}).get("file_path"))
                for b in blocks
                if isinstance(b, dict) and b.get("type") == "tool_use"
            )
            thinking_chars = sum(
                len(b.get("thinking", "")) for b in blocks if isinstance(b, dict) and b.get("type") == "thinking"
            )
            if not text_blocks and not tool_calls:
                return None
            combined = " ".join(text_blocks)
            return AssistantMessage(
                content=(
                    combined[:LEGACY_ASSISTANT_TRUNCATION] + "[...]"
                    if len(combined) > LEGACY_ASSISTANT_TRUNCATION
                    else combined
                ),
                timestamp=datetime.fromisoformat(data["timestamp"]),
                session_id=SessionId(data["sessionId"]),
                uuid=data["uuid"],
                tool_calls=tool_calls,
                thinking_chars=thinking_chars,
                claude_model=data["message"]["model"],
            )
        case _:
            return None


def legacy_messages(raw: bytes) -> list[TranscriptMessage]:
    messages: list[TranscriptMessage] = []
    for line in raw.split(b"\n"):
        if not line.strip():
            continue
        try:
            data = orjson.loads(line)
        except orjson.JSONDecodeError:
            continue
        if (msg := legacy_build_message(data)) is not None:
            messages.append(msg)
    return messages


# ---- the migrated path ----


def new_messages(raw: bytes) -> list[TranscriptMessage]:
    return list(to_messages(apply_spec(parse_events_from_bytes(raw), SENTIMENT_SPEC)))


def real_corpus() -> list[Path]:
    if not CLAUDE_PROJECTS_DIR.exists():
        return []
    paths = sorted(CLAUDE_PROJECTS_DIR.rglob("*.jsonl"), key=lambda p: p.stat().st_size)
    if not paths:
        return []
    agents = [p for p in paths if p.name.startswith("agent-")][:5]
    others = [p for p in paths if not p.name.startswith("agent-")]
    spread = [others[i] for i in range(0, len(others), max(1, len(others) // REAL_CORPUS_SAMPLE))]
    return list(dict.fromkeys(agents + spread))[:REAL_CORPUS_SAMPLE]


def synthetic_lines() -> Iterator[bytes]:
    base = {
        "parentUuid": None,
        "isSidechain": False,
        "uuid": "u",
        "timestamp": "2026-04-10T07:36:00.000Z",
        "sessionId": "s",
        "version": "2.1.92",
    }

    def user(content: str | list[dict[str, Any]], **over: Any) -> bytes:
        return orjson.dumps(base | {"type": "user", "message": {"role": "user", "content": content}} | over)

    yield user("fix the login bug please")
    yield user("   ")
    yield user("<system-reminder>x</system-reminder>")
    yield user("[Request interrupted by user] redo it")
    yield user("Stop hook feedback: keep going")
    yield user("ok")  # short but kept by SENTIMENT
    yield user("Base directory for this skill: /tmp\n# Skill")
    yield user("Help me: ### A ### B ### C ### D")
    yield user("real content", isCompactSummary=True, isVisibleInTranscriptOnly=True)
    yield user("one shot", entrypoint="sdk-cli")
    yield user("sidechain", isSidechain=True)
    yield user([{"type": "text", "text": "block one"}, {"type": "text", "text": "block two"}])
    yield user([{"type": "tool_result", "tool_use_id": "t", "content": "out", "is_error": False}])
    yield user("   leading and trailing   ")
    yield orjson.dumps(
        base
        | {
            "type": "assistant",
            "message": {
                "model": "claude-opus-4-7",
                "content": [
                    {"type": "text", "text": "let me look"},
                    {"type": "thinking", "thinking": "hmm 🤔"},
                    {"type": "tool_use", "id": "t1", "name": "Read", "input": {"file_path": "/x"}},
                ],
            },
        }
    )
    yield orjson.dumps(base | {"type": "assistant", "message": {"model": "<synthetic>", "content": [{"type": "text", "text": "noop"}]}})
    yield orjson.dumps(
        base | {"type": "assistant", "message": {"model": "m", "content": [{"type": "text", "text": "y" * 2000}]}}
    )
    yield orjson.dumps({"type": "queue-operation", "operation": "enqueue"})
    yield orjson.dumps(base | {"type": "summary", "summary": "x"})


def test_synthetic_message_parity() -> None:
    raw = b"\n".join(synthetic_lines())
    assert new_messages(raw) == legacy_messages(raw)


def test_synthetic_bucket_key_parity() -> None:
    raw = b"\n".join(synthetic_lines())
    assert extract_bucket_keys(new_messages(raw)) == extract_bucket_keys(legacy_messages(raw))


def test_fixture_message_parity() -> None:
    raw = FIXTURE_PATH.read_bytes()
    assert new_messages(raw) == legacy_messages(raw)


def test_fixture_bucket_key_parity() -> None:
    raw = FIXTURE_PATH.read_bytes()
    new_keys: list[BucketKey] = extract_bucket_keys(new_messages(raw))
    assert new_keys == extract_bucket_keys(legacy_messages(raw))


@pytest.mark.parametrize("path", real_corpus(), ids=lambda p: f"{p.parent.name}/{p.name}")
def test_real_corpus_message_parity(path: Path) -> None:
    raw = path.read_bytes()
    assert new_messages(raw) == legacy_messages(raw)


@pytest.mark.parametrize("path", real_corpus(), ids=lambda p: f"{p.parent.name}/{p.name}")
def test_real_corpus_bucket_key_parity(path: Path) -> None:
    raw = path.read_bytes()
    assert extract_bucket_keys(new_messages(raw)) == extract_bucket_keys(legacy_messages(raw))
