use chrono::{DateTime, FixedOffset};
use crossbeam_channel::{bounded, Receiver};
use memchr::memchr_iter;
use once_cell::sync::Lazy;
use pyo3::prelude::*;
use pyo3::sync::PyOnceLock;
use pyo3::types::{PyString, PyTuple, PyType};
use rayon::prelude::*;
use regex::Regex;
use rustc_hash::FxHashMap;
use serde::Deserialize;
use std::borrow::Cow;
use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};
use std::thread;
use walkdir::WalkDir;

const BUCKET_SECONDS: i64 = 180;
const ASSISTANT_TRUNCATION: usize = 1024;
const MIN_USER_TURNS_PER_SESSION: usize = 2;
const MIN_USER_CHARS: usize = 5;
const AVG_LINE_BYTES: usize = 1400;

type ScanEntry = (String, f64, Vec<(String, i64)>);

static PARSE_POOL: Lazy<rayon::ThreadPool> = Lazy::new(|| {
    let n = std::env::var("CC_SENTIMENT_PARSE_THREADS")
        .ok()
        .and_then(|s| s.parse::<usize>().ok())
        .unwrap_or_else(|| (num_cpus::get() * 2).min(32));
    rayon::ThreadPoolBuilder::new()
        .num_threads(n)
        .thread_name(|i| format!("cc-sentiment-parse-{i}"))
        .build()
        .expect("parse pool builds")
});

static JUNK_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(concat!(
        r"(?i)",
        r"<(?:system[_-](?:instruction|reminder)",
        r"|local-command-(?:stdout|caveat)",
        r"|command-(?:name|message|args)",
        r"|task-notification",
        r"|persisted-output",
        r"|output-file)\b",
        r"|Caveat: The messages below were generated by the user while running local commands\.",
        r"|\[Request interrupted by user",
        r"|Stop hook feedback:",
        r"|REMAINING_TASKS_ACKNOWLEDGED",
        r"|<<[a-z][a-z0-9-]*>>",
        r"|^Base directory for this skill:",
        r"|(?:###\s+[\w][\w \-]{0,30}\s+){3,}###",
    ))
    .expect("static regex compiles")
});

static USER_MSG_CLS: PyOnceLock<Py<PyType>> = PyOnceLock::new();
static ASSISTANT_MSG_CLS: PyOnceLock<Py<PyType>> = PyOnceLock::new();
static TOOL_CALL_CLS: PyOnceLock<Py<PyType>> = PyOnceLock::new();
static BUCKET_KEY_CLS: PyOnceLock<Py<PyType>> = PyOnceLock::new();

fn models_type<'py>(
    py: Python<'py>,
    cell: &'static PyOnceLock<Py<PyType>>,
    name: &str,
) -> PyResult<Bound<'py, PyType>> {
    let cached = cell.get_or_try_init(py, || -> PyResult<Py<PyType>> {
        let module = py.import("cc_sentiment.models")?;
        let cls = module.getattr(name)?.cast_into::<PyType>()?;
        Ok(cls.unbind())
    })?;
    Ok(cached.bind(py).clone())
}

#[derive(Deserialize)]
struct Envelope<'a> {
    #[serde(rename = "type", borrow, default)]
    kind: Option<Cow<'a, str>>,
    #[serde(borrow, default)]
    timestamp: Option<Cow<'a, str>>,
    #[serde(rename = "sessionId", borrow, default)]
    session_id: Option<Cow<'a, str>>,
    #[serde(rename = "isSidechain", default)]
    is_sidechain: bool,
    #[serde(rename = "isCompactSummary", default)]
    is_compact_summary: bool,
    #[serde(rename = "isVisibleInTranscriptOnly", default)]
    is_visible_in_transcript_only: bool,
    #[serde(borrow, default)]
    entrypoint: Option<Cow<'a, str>>,
    #[serde(borrow, default)]
    uuid: Option<Cow<'a, str>>,
    #[serde(borrow, default)]
    version: Option<Cow<'a, str>>,
    #[serde(borrow, default)]
    message: Option<MessageRaw<'a>>,
}

#[derive(Deserialize)]
struct MessageRaw<'a> {
    #[serde(borrow, default)]
    model: Option<Cow<'a, str>>,
    #[serde(borrow, default)]
    content: Option<Content<'a>>,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum Content<'a> {
    Text(#[serde(borrow)] Cow<'a, str>),
    Blocks(#[serde(borrow)] Vec<ContentBlock<'a>>),
}

#[derive(Deserialize)]
struct ContentBlock<'a> {
    #[serde(rename = "type", borrow, default)]
    kind: Option<Cow<'a, str>>,
    #[serde(borrow, default)]
    text: Option<Cow<'a, str>>,
    #[serde(borrow, default)]
    thinking: Option<Cow<'a, str>>,
    #[serde(borrow, default)]
    name: Option<Cow<'a, str>>,
    #[serde(borrow, default)]
    input: Option<InputBlock<'a>>,
}

#[derive(Deserialize)]
struct InputBlock<'a> {
    #[serde(rename = "file_path", borrow, default)]
    file_path: Option<Cow<'a, str>>,
}

enum Parsed {
    User {
        content: String,
        timestamp: DateTime<FixedOffset>,
        session_id: String,
        uuid: String,
        cc_version: String,
    },
    Assistant {
        content: String,
        timestamp: DateTime<FixedOffset>,
        session_id: String,
        uuid: String,
        claude_model: String,
        tool_calls: Vec<(String, Option<String>)>,
        thinking_chars: usize,
    },
}

fn extract_user_text(content: &Content<'_>) -> Option<String> {
    match content {
        Content::Text(s) => Some(s.to_string()),
        Content::Blocks(blocks) => {
            let parts: Vec<&str> = blocks
                .iter()
                .filter_map(|b| {
                    if b.kind.as_deref()? == "text" {
                        b.text.as_deref()
                    } else {
                        None
                    }
                })
                .collect();
            if parts.is_empty() {
                None
            } else {
                Some(parts.join(" "))
            }
        }
    }
}

fn truncate_at_chars(s: String, limit: usize) -> String {
    if s.len() <= limit {
        return s;
    }
    match s.char_indices().nth(limit) {
        Some((idx, _)) => {
            let mut out = s;
            out.truncate(idx);
            out.push_str("[...]");
            out
        }
        None => s,
    }
}

fn parse_envelope(env: Envelope<'_>) -> Option<Parsed> {
    if env.is_compact_summary || env.is_visible_in_transcript_only {
        return None;
    }
    if env.entrypoint.as_deref() == Some("sdk-cli") {
        return None;
    }
    let ts = DateTime::parse_from_rfc3339(env.timestamp.as_deref()?).ok()?;
    match env.kind.as_deref()? {
        "user" => {
            if env.is_sidechain {
                return None;
            }
            let msg = env.message?;
            let content_val = msg.content?;
            let content = extract_user_text(&content_val)?;
            if JUNK_RE.is_match(&content) {
                return None;
            }
            let trimmed = content.trim();
            if trimmed.is_empty() {
                return None;
            }
            Some(Parsed::User {
                content: trimmed.to_string(),
                timestamp: ts,
                session_id: env.session_id?.into_owned(),
                uuid: env.uuid?.into_owned(),
                cc_version: env.version.map(|v| v.into_owned()).unwrap_or_default(),
            })
        }
        "assistant" => {
            let msg = env.message?;
            let model = msg.model?;
            if model == "<synthetic>" {
                return None;
            }
            let blocks = match msg.content? {
                Content::Blocks(v) => v,
                Content::Text(_) => return None,
            };
            let mut text_parts: Vec<String> = Vec::with_capacity(4);
            let mut tool_calls: Vec<(String, Option<String>)> = Vec::with_capacity(4);
            let mut thinking_chars: usize = 0;
            for b in blocks {
                match b.kind.as_deref() {
                    Some("text") => {
                        if let Some(t) = b.text {
                            text_parts.push(t.into_owned());
                        }
                    }
                    Some("tool_use") => {
                        let Some(name) = b.name else {
                            continue;
                        };
                        let fp = b
                            .input
                            .and_then(|i| i.file_path)
                            .map(|c| c.into_owned());
                        tool_calls.push((name.into_owned(), fp));
                    }
                    Some("thinking") => {
                        if let Some(t) = b.thinking {
                            thinking_chars += bytecount::num_chars(t.as_bytes());
                        }
                    }
                    _ => {}
                }
            }
            if text_parts.is_empty() && tool_calls.is_empty() {
                return None;
            }
            let combined = text_parts.join(" ");
            let content = truncate_at_chars(combined, ASSISTANT_TRUNCATION);
            Some(Parsed::Assistant {
                content,
                timestamp: ts,
                session_id: env.session_id?.into_owned(),
                uuid: env.uuid?.into_owned(),
                claude_model: model.into_owned(),
                tool_calls,
                thinking_chars,
            })
        }
        _ => None,
    }
}

fn build_tool_calls<'py>(
    py: Python<'py>,
    calls: Vec<(String, Option<String>)>,
) -> PyResult<Bound<'py, PyTuple>> {
    let cls = models_type(py, &TOOL_CALL_CLS, "ToolCall")?;
    let items: Vec<Bound<'py, PyAny>> = calls
        .into_iter()
        .map(|(name, fp)| cls.call1((name, fp)))
        .collect::<PyResult<Vec<_>>>()?;
    PyTuple::new(py, items)
}

fn parsed_to_py<'py>(py: Python<'py>, parsed: Parsed) -> PyResult<Bound<'py, PyAny>> {
    match parsed {
        Parsed::User {
            content,
            timestamp,
            session_id,
            uuid,
            cc_version,
        } => {
            let cls = models_type(py, &USER_MSG_CLS, "UserMessage")?;
            let empty_calls = PyTuple::empty(py);
            cls.call1((
                content,
                timestamp,
                session_id,
                uuid,
                empty_calls,
                0usize,
                cc_version,
            ))
        }
        Parsed::Assistant {
            content,
            timestamp,
            session_id,
            uuid,
            claude_model,
            tool_calls,
            thinking_chars,
        } => {
            let cls = models_type(py, &ASSISTANT_MSG_CLS, "AssistantMessage")?;
            let calls_tuple = build_tool_calls(py, tool_calls)?;
            cls.call1((
                content,
                timestamp,
                session_id,
                uuid,
                calls_tuple,
                thinking_chars,
                claude_model,
            ))
        }
    }
}

fn handle_parse_line(
    line: &[u8],
    messages: &mut Vec<Parsed>,
    by_session: &mut FxHashMap<String, Vec<(i64, bool, bool)>>,
) {
    if line.is_empty() || line.iter().all(|&b| b.is_ascii_whitespace()) {
        return;
    }
    let Ok(env) = sonic_rs::from_slice::<Envelope>(line) else {
        return;
    };
    let Some(parsed) = parse_envelope(env) else {
        return;
    };
    let (sid, ts_secs, is_user, is_substantive) = match &parsed {
        Parsed::User {
            session_id,
            timestamp,
            content,
            ..
        } => (
            session_id.clone(),
            timestamp.timestamp(),
            true,
            content.trim().chars().count() >= MIN_USER_CHARS,
        ),
        Parsed::Assistant {
            session_id,
            timestamp,
            ..
        } => (session_id.clone(), timestamp.timestamp(), false, false),
    };
    by_session
        .entry(sid)
        .or_default()
        .push((ts_secs, is_user, is_substantive));
    messages.push(parsed);
}

fn finalize_bucket_keys(
    by_session: FxHashMap<String, Vec<(i64, bool, bool)>>,
) -> Vec<(String, i64)> {
    let mut keys: Vec<(String, i64)> = Vec::new();
    for (session_id, mut entries) in by_session {
        if entries.iter().filter(|(_, u, _)| *u).count() < MIN_USER_TURNS_PER_SESSION {
            continue;
        }
        entries.sort_by_key(|e| e.0);
        let session_start = (entries[0].0 / BUCKET_SECONDS) * BUCKET_SECONDS;
        let mut grouped: BTreeMap<i64, (bool, bool)> = BTreeMap::new();
        for (ts, is_user, is_substantive) in &entries {
            let idx = (ts - session_start) / BUCKET_SECONDS;
            let slot = grouped.entry(idx).or_insert((false, false));
            if *is_user {
                if *is_substantive {
                    slot.0 = true;
                }
            } else {
                slot.1 = true;
            }
        }
        for (idx, (has_substantive_user, has_assistant)) in grouped {
            if !has_substantive_user || !has_assistant {
                continue;
            }
            keys.push((session_id.clone(), idx));
        }
    }
    keys
}

#[derive(Clone, Copy)]
struct FileFilter<'a> {
    name_contains: Option<&'a str>,
    limit: Option<usize>,
    known_mtimes: Option<&'a HashMap<String, f64>>,
}

fn discover(dir: &Path, filter: FileFilter<'_>) -> Vec<(PathBuf, f64)> {
    let mut found: Vec<(PathBuf, f64)> = WalkDir::new(dir)
        .into_iter()
        .filter_map(|entry| entry.ok())
        .filter(|e| e.file_type().is_file())
        .filter(|e| e.path().extension().and_then(|s| s.to_str()) == Some("jsonl"))
        .filter(|e| {
            filter
                .name_contains
                .map(|needle| {
                    e.file_name()
                        .to_str()
                        .map(|n| n.contains(needle))
                        .unwrap_or(false)
                })
                .unwrap_or(true)
        })
        .filter_map(|e| {
            let meta = e.metadata().ok()?;
            let mtime = meta
                .modified()
                .ok()?
                .duration_since(std::time::UNIX_EPOCH)
                .ok()?
                .as_secs_f64();
            Some((e.into_path(), mtime))
        })
        .filter(|(path, mtime)| {
            let Some(known) = filter.known_mtimes else {
                return true;
            };
            match known.get(path.to_string_lossy().as_ref()) {
                None => true,
                Some(prev) => *prev < *mtime,
            }
        })
        .collect();
    found.sort_by(|a, b| a.0.cmp(&b.0));
    if let Some(n) = filter.limit {
        found.truncate(n);
    }
    found
}

struct ParsedFile {
    path: String,
    mtime: f64,
    bucket_keys: Vec<(String, i64)>,
    messages: Vec<Parsed>,
}

fn parse_file_internal(path: &str, mtime: f64) -> std::io::Result<ParsedFile> {
    let bytes = std::fs::read(path)?;
    let est_lines = bytes.len() / AVG_LINE_BYTES + 1;
    let mut messages: Vec<Parsed> = Vec::with_capacity(est_lines);
    let mut by_session: FxHashMap<String, Vec<(i64, bool, bool)>> = FxHashMap::default();
    let mut start = 0usize;
    for pos in memchr_iter(b'\n', &bytes) {
        handle_parse_line(&bytes[start..pos], &mut messages, &mut by_session);
        start = pos + 1;
    }
    if start < bytes.len() {
        handle_parse_line(&bytes[start..], &mut messages, &mut by_session);
    }
    Ok(ParsedFile {
        path: path.to_string(),
        mtime,
        bucket_keys: finalize_bucket_keys(by_session),
        messages,
    })
}

fn parsed_file_to_py<'py>(py: Python<'py>, pf: ParsedFile) -> PyResult<Bound<'py, PyAny>> {
    let bk_cls = models_type(py, &BUCKET_KEY_CLS, "BucketKey")?;
    let bk_items: Vec<Bound<'py, PyAny>> = pf
        .bucket_keys
        .into_iter()
        .map(|(sid, idx)| bk_cls.call1((sid, idx)))
        .collect::<PyResult<Vec<_>>>()?;
    let bk = PyTuple::new(py, bk_items)?;

    let msg_items: Vec<Bound<'py, PyAny>> = pf
        .messages
        .into_iter()
        .map(|p| parsed_to_py(py, p))
        .collect::<PyResult<Vec<_>>>()?;
    let msgs = PyTuple::new(py, msg_items)?;

    let out = PyTuple::new(
        py,
        [
            PyString::new(py, &pf.path).into_any(),
            pf.mtime.into_pyobject(py)?.into_any(),
            bk.into_any(),
            msgs.into_any(),
        ],
    )?;
    Ok(out.into_any())
}

#[pyclass]
pub struct ParseStream {
    rx: Receiver<ParsedFile>,
}

#[pymethods]
impl ParseStream {
    fn recv<'py>(&self, py: Python<'py>) -> PyResult<Option<Bound<'py, PyAny>>> {
        let opt = py.detach(|| self.rx.recv().ok());
        match opt {
            None => Ok(None),
            Some(pf) => Ok(Some(parsed_file_to_py(py, pf)?)),
        }
    }

    fn recv_many<'py>(
        &self,
        py: Python<'py>,
        max: usize,
    ) -> PyResult<Vec<Bound<'py, PyAny>>> {
        let batch: Vec<ParsedFile> = py.detach(|| {
            let mut out: Vec<ParsedFile> = Vec::new();
            match self.rx.recv() {
                Ok(pf) => out.push(pf),
                Err(_) => return out,
            }
            while out.len() < max {
                match self.rx.try_recv() {
                    Ok(pf) => out.push(pf),
                    Err(_) => break,
                }
            }
            out
        });
        batch
            .into_iter()
            .map(|pf| parsed_file_to_py(py, pf))
            .collect()
    }
}

#[pyfunction]
fn stream_parse(paths: Vec<(String, f64)>, prefetch: usize) -> PyResult<ParseStream> {
    let capacity = prefetch.max(1);
    let (tx, rx) = bounded::<ParsedFile>(capacity);
    thread::spawn(move || {
        PARSE_POOL.install(|| {
            paths
                .into_par_iter()
                .for_each_with(tx, |tx, (path, mtime)| {
                    if let Ok(pf) = parse_file_internal(&path, mtime) {
                        let _ = tx.send(pf);
                    }
                });
        });
    });
    Ok(ParseStream { rx })
}

#[pyfunction]
#[pyo3(signature = (dir, *, name_contains=None, limit=None, known_mtimes=None))]
fn scan_bucket_keys(
    py: Python<'_>,
    dir: &str,
    name_contains: Option<&str>,
    limit: Option<usize>,
    known_mtimes: Option<HashMap<String, f64>>,
) -> PyResult<Vec<ScanEntry>> {
    let dir = PathBuf::from(dir);
    Ok(py.detach(move || {
        let filter = FileFilter {
            name_contains,
            limit,
            known_mtimes: known_mtimes.as_ref(),
        };
        let files = discover(&dir, filter);
        PARSE_POOL.install(|| {
            files
                .into_par_iter()
                .filter_map(|(path, mtime)| {
                    let pf = parse_file_internal(&path.to_string_lossy(), mtime).ok()?;
                    Some((pf.path, pf.mtime, pf.bucket_keys))
                })
                .collect()
        })
    }))
}

#[pymodule]
fn _transcripts_rs(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(stream_parse, m)?)?;
    m.add_function(wrap_pyfunction!(scan_bucket_keys, m)?)?;
    m.add_class::<ParseStream>()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse_line(line: &str) -> Option<Parsed> {
        let env: Envelope = sonic_rs::from_str(line).ok()?;
        parse_envelope(env)
    }

    #[test]
    fn parses_user_string_content() {
        let line = r#"{"parentUuid":null,"isSidechain":false,"type":"user","message":{"role":"user","content":"hello"},"uuid":"u","timestamp":"2026-04-10T07:36:00.000Z","sessionId":"s","version":"2.1.92"}"#;
        let parsed = parse_line(line).unwrap();
        match parsed {
            Parsed::User {
                content,
                cc_version,
                ..
            } => {
                assert_eq!(content, "hello");
                assert_eq!(cc_version, "2.1.92");
            }
            _ => panic!("expected user"),
        }
    }

    #[test]
    fn skips_sdk_cli_entrypoint() {
        let line = r#"{"type":"user","message":{"role":"user","content":"hi"},"entrypoint":"sdk-cli","uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s","version":"2.1.92"}"#;
        assert!(parse_line(line).is_none());
    }

    #[test]
    fn skips_compact_summary_user_message() {
        let line = r#"{"type":"user","isSidechain":false,"message":{"role":"user","content":"This session is being continued from a previous conversation that ran out of context.\n\nSummary: did stuff"},"isCompactSummary":true,"isVisibleInTranscriptOnly":true,"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s","version":"2.1.111","entrypoint":"sdk-ts"}"#;
        assert!(parse_line(line).is_none());
    }

    #[test]
    fn skips_visible_in_transcript_only_user_message() {
        let line = r#"{"type":"user","isSidechain":false,"message":{"role":"user","content":"real-looking content that would otherwise pass filters"},"isVisibleInTranscriptOnly":true,"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s","version":"2.1.92"}"#;
        assert!(parse_line(line).is_none());
    }

    #[test]
    fn skips_synthetic_assistant() {
        let line = r#"{"type":"assistant","message":{"model":"<synthetic>","content":[{"type":"text","text":"x"}]},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s"}"#;
        assert!(parse_line(line).is_none());
    }

    #[test]
    fn skips_user_system_reminder() {
        let line = r#"{"type":"user","isSidechain":false,"message":{"role":"user","content":"<system-reminder>x</system-reminder>"},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s","version":"2.1.92"}"#;
        assert!(parse_line(line).is_none());
    }

    #[test]
    fn skips_skill_directory_inject() {
        let line = r#"{"type":"user","isSidechain":false,"message":{"role":"user","content":"Base directory for this skill: /Users/me/.claude/plugins/cache/playwright-cli/0.0.1\n\n# Browser Automation"},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s","version":"2.1.92"}"#;
        assert!(parse_line(line).is_none());
    }

    #[test]
    fn skips_inline_markdown_menu_paste() {
        let line = r#"{"type":"user","isSidechain":false,"message":{"role":"user","content":"Help me with: ### Keyboard ### Mouse ### Save as ### Tabs ### DevTools"},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s","version":"2.1.92"}"#;
        assert!(parse_line(line).is_none());
    }

    #[test]
    fn allows_single_h3_heading() {
        let line = r#"{"type":"user","isSidechain":false,"message":{"role":"user","content":"Reading the docs:\n### Setup\nWhat config?"},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s","version":"2.1.92"}"#;
        let parsed = parse_line(line).unwrap();
        match parsed {
            Parsed::User { content, .. } => assert!(content.contains("Setup")),
            _ => panic!("expected user"),
        }
    }

    #[test]
    fn truncates_long_assistant() {
        let long = "x".repeat(2000);
        let line = format!(
            r#"{{"type":"assistant","message":{{"model":"m","content":[{{"type":"text","text":"{long}"}}]}},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s"}}"#
        );
        let parsed = parse_line(&line).unwrap();
        match parsed {
            Parsed::Assistant { content, .. } => {
                assert_eq!(
                    content.chars().count(),
                    ASSISTANT_TRUNCATION + "[...]".chars().count()
                );
                assert!(content.ends_with("[...]"));
            }
            _ => panic!("expected assistant"),
        }
    }

    #[test]
    fn extracts_tool_calls_with_file_path() {
        let line = r#"{"type":"assistant","message":{"model":"m","content":[{"type":"tool_use","name":"Read","input":{"file_path":"/a.py"}},{"type":"text","text":"ok"}]},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s"}"#;
        let parsed = parse_line(line).unwrap();
        match parsed {
            Parsed::Assistant {
                tool_calls,
                content,
                ..
            } => {
                assert_eq!(content, "ok");
                assert_eq!(tool_calls.len(), 1);
                assert_eq!(tool_calls[0].0, "Read");
                assert_eq!(tool_calls[0].1.as_deref(), Some("/a.py"));
            }
            _ => panic!("expected assistant"),
        }
    }

    #[test]
    fn user_list_content_joins_text_blocks() {
        let line = r#"{"type":"user","isSidechain":false,"message":{"role":"user","content":[{"type":"text","text":"a"},{"type":"text","text":"b"}]},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s","version":"2.1.92"}"#;
        let parsed = parse_line(line).unwrap();
        match parsed {
            Parsed::User { content, .. } => assert_eq!(content, "a b"),
            _ => panic!("expected user"),
        }
    }

    #[test]
    fn parse_file_internal_drains_messages_and_bucket_keys() {
        let tmp = std::env::temp_dir().join(format!(
            "cc_sentiment_pfi_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&tmp).unwrap();
        let path = tmp.join("s.jsonl");
        let content = concat!(
            r#"{"type":"user","isSidechain":false,"message":{"role":"user","content":"hi"},"uuid":"u1","timestamp":"2026-04-10T07:36:00.000Z","sessionId":"s","version":"2.1.92"}"#,
            "\n",
            r#"{"type":"assistant","message":{"model":"m","content":[{"type":"text","text":"ok"}]},"uuid":"u2","timestamp":"2026-04-10T07:36:05.000Z","sessionId":"s","version":"2.1.92"}"#,
            "\n",
            r#"{"type":"user","isSidechain":false,"message":{"role":"user","content":"thanks"},"uuid":"u3","timestamp":"2026-04-10T07:36:10.000Z","sessionId":"s","version":"2.1.92"}"#,
            "\n"
        );
        std::fs::write(&path, content).unwrap();
        let pf = parse_file_internal(path.to_str().unwrap(), 42.0).unwrap();
        assert_eq!(pf.mtime, 42.0);
        assert_eq!(pf.messages.len(), 3);
        assert_eq!(pf.bucket_keys.len(), 1);
        assert_eq!(pf.bucket_keys[0].0, "s");
        assert_eq!(pf.bucket_keys[0].1, 0);
        std::fs::remove_dir_all(&tmp).unwrap();
    }

    #[test]
    fn discover_respects_name_filter_and_limit() {
        let tmp = std::env::temp_dir().join(format!("cc_sentiment_test_{}", std::process::id()));
        std::fs::create_dir_all(&tmp).unwrap();
        std::fs::write(tmp.join("alpha.jsonl"), b"").unwrap();
        std::fs::write(tmp.join("beta.jsonl"), b"").unwrap();
        std::fs::write(tmp.join("ignore.txt"), b"").unwrap();
        let filter = FileFilter {
            name_contains: Some("alpha"),
            limit: None,
            known_mtimes: None,
        };
        let found = discover(&tmp, filter);
        assert_eq!(found.len(), 1);
        assert!(found[0].0.ends_with("alpha.jsonl"));
        let filter2 = FileFilter {
            name_contains: None,
            limit: Some(1),
            known_mtimes: None,
        };
        assert_eq!(discover(&tmp, filter2).len(), 1);
        std::fs::remove_dir_all(&tmp).unwrap();
    }
}
