use chrono::DateTime;
use once_cell::sync::Lazy;
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyList};
use rayon::prelude::*;
use regex::Regex;
use serde_json::Value;
use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

const BUCKET_SECONDS: i64 = 300;
const ASSISTANT_TRUNCATION: usize = 1024;
const MIN_USER_TURNS_PER_SESSION: usize = 2;

static JUNK_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(concat!(
        r"(?i)",
        r"<(?:system[_-](?:instruction|reminder)",
        r"|local-command-(?:stdout|caveat)",
        r"|command-(?:name|message|args)",
        r"|task-notification",
        r"|persisted-output",
        r"|output-file)\b",
        r"|Caveat: The messages below were generated by the user while running local commands\.",
        r"|This session is being continued from a previous conversation that ran out of context\.",
        r"|\[Request interrupted by user for tool use\]",
    ))
    .expect("static regex compiles")
});

enum Parsed {
    User {
        content: String,
        timestamp: String,
        session_id: String,
        uuid: String,
        cc_version: String,
    },
    Assistant {
        content: String,
        timestamp: String,
        session_id: String,
        uuid: String,
        claude_model: String,
        tool_calls: Vec<(String, Option<String>)>,
        thinking_chars: usize,
    },
}

fn get_str<'a>(v: &'a Value, key: &str) -> Option<&'a str> {
    v.get(key)?.as_str()
}

fn extract_user_content(raw: &Value) -> Option<String> {
    match raw {
        Value::String(s) => Some(s.clone()),
        Value::Array(arr) => {
            let parts: Vec<&str> = arr
                .iter()
                .filter_map(|block| {
                    let obj = block.as_object()?;
                    if obj.get("type")?.as_str()? != "text" {
                        return None;
                    }
                    obj.get("text")?.as_str()
                })
                .collect();
            if parts.is_empty() {
                None
            } else {
                Some(parts.join(" "))
            }
        }
        _ => None,
    }
}

fn parse_value(data: &Value) -> Option<Parsed> {
    if get_str(data, "entrypoint") == Some("sdk-cli") {
        return None;
    }
    match get_str(data, "type")? {
        "queue-operation" => None,
        "user" => {
            if data
                .get("isSidechain")
                .and_then(|v| v.as_bool())
                .unwrap_or(false)
            {
                return None;
            }
            let message = data.get("message")?;
            let content = extract_user_content(message.get("content")?)?;
            if JUNK_RE.is_match(&content) {
                return None;
            }
            let trimmed = content.trim();
            if trimmed.is_empty() {
                return None;
            }
            Some(Parsed::User {
                content: trimmed.to_string(),
                timestamp: get_str(data, "timestamp")?.to_string(),
                session_id: get_str(data, "sessionId")?.to_string(),
                uuid: get_str(data, "uuid")?.to_string(),
                cc_version: get_str(data, "version")?.to_string(),
            })
        }
        "assistant" => {
            let message = data.get("message")?;
            let model = get_str(message, "model")?;
            if model == "<synthetic>" {
                return None;
            }
            let blocks = message.get("content")?.as_array()?;
            let mut text_parts: Vec<&str> = Vec::new();
            let mut tool_calls: Vec<(String, Option<String>)> = Vec::new();
            let mut thinking_chars: usize = 0;
            for block in blocks {
                let Some(obj) = block.as_object() else {
                    continue;
                };
                match obj.get("type").and_then(|v| v.as_str()) {
                    Some("text") => {
                        if let Some(t) = obj.get("text").and_then(|v| v.as_str()) {
                            text_parts.push(t);
                        }
                    }
                    Some("tool_use") => {
                        let Some(name) = obj.get("name").and_then(|v| v.as_str()) else {
                            continue;
                        };
                        let file_path = obj
                            .get("input")
                            .and_then(|v| v.as_object())
                            .and_then(|o| o.get("file_path"))
                            .and_then(|v| v.as_str())
                            .map(str::to_string);
                        tool_calls.push((name.to_string(), file_path));
                    }
                    Some("thinking") => {
                        if let Some(t) = obj.get("thinking").and_then(|v| v.as_str()) {
                            thinking_chars += t.chars().count();
                        }
                    }
                    _ => {}
                }
            }
            if text_parts.is_empty() && tool_calls.is_empty() {
                return None;
            }
            let combined = text_parts.join(" ");
            let content = if combined.chars().count() > ASSISTANT_TRUNCATION {
                let truncated: String = combined.chars().take(ASSISTANT_TRUNCATION).collect();
                format!("{truncated}[...]")
            } else {
                combined
            };
            Some(Parsed::Assistant {
                content,
                timestamp: get_str(data, "timestamp")?.to_string(),
                session_id: get_str(data, "sessionId")?.to_string(),
                uuid: get_str(data, "uuid")?.to_string(),
                claude_model: model.to_string(),
                tool_calls,
                thinking_chars,
            })
        }
        _ => None,
    }
}

fn parsed_to_dict<'py>(py: Python<'py>, parsed: Parsed) -> PyResult<Bound<'py, PyDict>> {
    let d = PyDict::new(py);
    match parsed {
        Parsed::User {
            content,
            timestamp,
            session_id,
            uuid,
            cc_version,
        } => {
            d.set_item("kind", "user")?;
            d.set_item("content", content)?;
            d.set_item("timestamp", timestamp)?;
            d.set_item("session_id", session_id)?;
            d.set_item("uuid", uuid)?;
            d.set_item("cc_version", cc_version)?;
        }
        Parsed::Assistant {
            content,
            timestamp,
            session_id,
            uuid,
            claude_model,
            tool_calls,
            thinking_chars,
        } => {
            d.set_item("kind", "assistant")?;
            d.set_item("content", content)?;
            d.set_item("timestamp", timestamp)?;
            d.set_item("session_id", session_id)?;
            d.set_item("uuid", uuid)?;
            d.set_item("claude_model", claude_model)?;
            d.set_item("thinking_chars", thinking_chars)?;
            let calls = PyList::empty(py);
            for (name, fp) in tool_calls {
                let tc = PyDict::new(py);
                tc.set_item("name", name)?;
                if let Some(p) = fp {
                    tc.set_item("file_path", p)?;
                }
                calls.append(tc)?;
            }
            d.set_item("tool_calls", calls)?;
        }
    }
    Ok(d)
}

fn parse_lines(content: &str) -> Vec<Parsed> {
    content
        .lines()
        .filter(|l| !l.trim().is_empty())
        .filter_map(|l| serde_json::from_str::<Value>(l).ok())
        .filter_map(|data| parse_value(&data))
        .collect()
}

fn bucket_classify(data: &Value) -> Option<(String, i64, bool)> {
    if get_str(data, "entrypoint") == Some("sdk-cli") {
        return None;
    }
    let is_user = match get_str(data, "type")? {
        "queue-operation" => return None,
        "user" => {
            if data
                .get("isSidechain")
                .and_then(|v| v.as_bool())
                .unwrap_or(false)
            {
                return None;
            }
            let message = data.get("message")?;
            let content = extract_user_content(message.get("content")?)?;
            if JUNK_RE.is_match(&content) {
                return None;
            }
            if content.trim().is_empty() {
                return None;
            }
            true
        }
        "assistant" => {
            let message = data.get("message")?;
            if get_str(message, "model")? == "<synthetic>" {
                return None;
            }
            let blocks = message.get("content")?.as_array()?;
            let has_text = blocks.iter().any(|b| {
                b.as_object()
                    .and_then(|o| o.get("type").and_then(|t| t.as_str()))
                    == Some("text")
            });
            let has_tool = blocks.iter().any(|b| {
                b.as_object()
                    .and_then(|o| o.get("type").and_then(|t| t.as_str()))
                    == Some("tool_use")
            });
            if !has_text && !has_tool {
                return None;
            }
            false
        }
        _ => return None,
    };
    let session_id = get_str(data, "sessionId")?.to_string();
    let ts_secs = DateTime::parse_from_rfc3339(get_str(data, "timestamp")?)
        .ok()?
        .timestamp();
    Some((session_id, ts_secs, is_user))
}

fn bucket_keys_from_bytes(bytes: &[u8]) -> Vec<(String, i64)> {
    let mut by_session: HashMap<String, Vec<(i64, bool)>> = HashMap::new();
    for line in bytes.split(|&b| b == b'\n') {
        if line.iter().all(|&b| b.is_ascii_whitespace()) {
            continue;
        }
        let Ok(data) = serde_json::from_slice::<Value>(line) else {
            continue;
        };
        let Some((session_id, ts_secs, is_user)) = bucket_classify(&data) else {
            continue;
        };
        by_session
            .entry(session_id)
            .or_default()
            .push((ts_secs, is_user));
    }
    let mut keys: Vec<(String, i64)> = Vec::new();
    for (session_id, mut entries) in by_session {
        if entries.iter().filter(|(_, u)| *u).count() < MIN_USER_TURNS_PER_SESSION {
            continue;
        }
        entries.sort_by_key(|e| e.0);
        let session_start = (entries[0].0 / BUCKET_SECONDS) * BUCKET_SECONDS;
        let mut grouped: BTreeMap<i64, (bool, bool)> = BTreeMap::new();
        for (ts, is_user) in &entries {
            let idx = (ts - session_start) / BUCKET_SECONDS;
            let slot = grouped.entry(idx).or_insert((false, false));
            if *is_user {
                slot.0 = true;
            } else {
                slot.1 = true;
            }
        }
        for (idx, (has_user, has_assistant)) in grouped {
            if !has_user || !has_assistant {
                continue;
            }
            keys.push((session_id.clone(), idx));
        }
    }
    keys
}

#[derive(Clone, Copy)]
struct FileFilter<'a> {
    name_contains: Option<&'a str>,
    limit: Option<usize>,
    known_mtimes: Option<&'a HashMap<String, f64>>,
}

fn discover(dir: &Path, filter: FileFilter<'_>) -> Vec<(PathBuf, f64)> {
    let mut found: Vec<(PathBuf, f64)> = WalkDir::new(dir)
        .into_iter()
        .filter_map(|entry| entry.ok())
        .filter(|e| e.file_type().is_file())
        .filter(|e| e.path().extension().and_then(|s| s.to_str()) == Some("jsonl"))
        .filter(|e| {
            filter
                .name_contains
                .map(|needle| {
                    e.file_name()
                        .to_str()
                        .map(|n| n.contains(needle))
                        .unwrap_or(false)
                })
                .unwrap_or(true)
        })
        .filter_map(|e| {
            let meta = e.metadata().ok()?;
            let mtime = meta
                .modified()
                .ok()?
                .duration_since(std::time::UNIX_EPOCH)
                .ok()?
                .as_secs_f64();
            Some((e.into_path(), mtime))
        })
        .filter(|(path, mtime)| {
            let Some(known) = filter.known_mtimes else {
                return true;
            };
            match known.get(path.to_string_lossy().as_ref()) {
                None => true,
                Some(prev) => *prev < *mtime,
            }
        })
        .collect();
    found.sort_by(|a, b| a.0.cmp(&b.0));
    if let Some(n) = filter.limit {
        found.truncate(n);
    }
    found
}

#[pyfunction]
fn parse_line(py: Python<'_>, line: &str) -> PyResult<Option<Py<PyDict>>> {
    let parsed = py.detach(|| {
        serde_json::from_str::<Value>(line)
            .ok()
            .and_then(|data| parse_value(&data))
    });
    match parsed {
        Some(p) => Ok(Some(parsed_to_dict(py, p)?.unbind())),
        None => Ok(None),
    }
}

#[pyfunction]
fn parse_file(py: Python<'_>, path: &str) -> PyResult<Vec<Py<PyDict>>> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| pyo3::exceptions::PyOSError::new_err(e.to_string()))?;
    let parsed: Vec<Parsed> = py.detach(|| parse_lines(&content));
    parsed
        .into_iter()
        .map(|p| Ok(parsed_to_dict(py, p)?.unbind()))
        .collect()
}

#[pyfunction]
fn bucket_keys_for(py: Python<'_>, path: &str) -> PyResult<Vec<(String, i64)>> {
    let content =
        std::fs::read(path).map_err(|e| pyo3::exceptions::PyOSError::new_err(e.to_string()))?;
    Ok(py.detach(|| bucket_keys_from_bytes(&content)))
}

#[pyfunction]
#[pyo3(signature = (dir, *, name_contains=None, limit=None, known_mtimes=None))]
fn scan_bucket_keys(
    py: Python<'_>,
    dir: &str,
    name_contains: Option<&str>,
    limit: Option<usize>,
    known_mtimes: Option<HashMap<String, f64>>,
) -> PyResult<Vec<(String, f64, Vec<(String, i64)>)>> {
    let dir = PathBuf::from(dir);
    Ok(py.detach(move || {
        let filter = FileFilter {
            name_contains,
            limit,
            known_mtimes: known_mtimes.as_ref(),
        };
        let files = discover(&dir, filter);
        files
            .into_par_iter()
            .filter_map(|(path, mtime)| {
                let bytes = std::fs::read(&path).ok()?;
                let keys = bucket_keys_from_bytes(&bytes);
                Some((path.to_string_lossy().into_owned(), mtime, keys))
            })
            .collect()
    }))
}

#[pymodule]
fn _transcripts_rs(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(parse_line, m)?)?;
    m.add_function(wrap_pyfunction!(parse_file, m)?)?;
    m.add_function(wrap_pyfunction!(bucket_keys_for, m)?)?;
    m.add_function(wrap_pyfunction!(scan_bucket_keys, m)?)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_user_string_content() {
        let line = r#"{"parentUuid":null,"isSidechain":false,"type":"user","message":{"role":"user","content":"hello"},"uuid":"u","timestamp":"2026-04-10T07:36:00.000Z","sessionId":"s","version":"2.1.92"}"#;
        let data: Value = serde_json::from_str(line).unwrap();
        let parsed = parse_value(&data).unwrap();
        match parsed {
            Parsed::User { content, cc_version, .. } => {
                assert_eq!(content, "hello");
                assert_eq!(cc_version, "2.1.92");
            }
            _ => panic!("expected user"),
        }
    }

    #[test]
    fn skips_sdk_cli_entrypoint() {
        let line = r#"{"type":"user","message":{"role":"user","content":"hi"},"entrypoint":"sdk-cli","uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s","version":"2.1.92"}"#;
        let data: Value = serde_json::from_str(line).unwrap();
        assert!(parse_value(&data).is_none());
    }

    #[test]
    fn skips_synthetic_assistant() {
        let line = r#"{"type":"assistant","message":{"model":"<synthetic>","content":[{"type":"text","text":"x"}]},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s"}"#;
        let data: Value = serde_json::from_str(line).unwrap();
        assert!(parse_value(&data).is_none());
    }

    #[test]
    fn skips_user_system_reminder() {
        let line = r#"{"type":"user","isSidechain":false,"message":{"role":"user","content":"<system-reminder>x</system-reminder>"},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s","version":"2.1.92"}"#;
        let data: Value = serde_json::from_str(line).unwrap();
        assert!(parse_value(&data).is_none());
    }

    #[test]
    fn truncates_long_assistant() {
        let long = "x".repeat(2000);
        let line = format!(
            r#"{{"type":"assistant","message":{{"model":"m","content":[{{"type":"text","text":"{long}"}}]}},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s"}}"#
        );
        let data: Value = serde_json::from_str(&line).unwrap();
        let parsed = parse_value(&data).unwrap();
        match parsed {
            Parsed::Assistant { content, .. } => {
                assert_eq!(content.chars().count(), ASSISTANT_TRUNCATION + "[...]".chars().count());
                assert!(content.ends_with("[...]"));
            }
            _ => panic!("expected assistant"),
        }
    }

    #[test]
    fn extracts_tool_calls_with_file_path() {
        let line = r#"{"type":"assistant","message":{"model":"m","content":[{"type":"tool_use","name":"Read","input":{"file_path":"/a.py"}},{"type":"text","text":"ok"}]},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s"}"#;
        let data: Value = serde_json::from_str(line).unwrap();
        let parsed = parse_value(&data).unwrap();
        match parsed {
            Parsed::Assistant { tool_calls, content, .. } => {
                assert_eq!(content, "ok");
                assert_eq!(tool_calls.len(), 1);
                assert_eq!(tool_calls[0].0, "Read");
                assert_eq!(tool_calls[0].1.as_deref(), Some("/a.py"));
            }
            _ => panic!("expected assistant"),
        }
    }

    #[test]
    fn user_list_content_joins_text_blocks() {
        let line = r#"{"type":"user","isSidechain":false,"message":{"role":"user","content":[{"type":"text","text":"a"},{"type":"text","text":"b"}]},"uuid":"u","timestamp":"2026-04-10T07:36:00Z","sessionId":"s","version":"2.1.92"}"#;
        let data: Value = serde_json::from_str(line).unwrap();
        let parsed = parse_value(&data).unwrap();
        match parsed {
            Parsed::User { content, .. } => assert_eq!(content, "a b"),
            _ => panic!("expected user"),
        }
    }

    #[test]
    fn discover_respects_name_filter_and_limit() {
        let tmp = std::env::temp_dir().join(format!("cc_sentiment_test_{}", std::process::id()));
        std::fs::create_dir_all(&tmp).unwrap();
        std::fs::write(tmp.join("alpha.jsonl"), b"").unwrap();
        std::fs::write(tmp.join("beta.jsonl"), b"").unwrap();
        std::fs::write(tmp.join("ignore.txt"), b"").unwrap();
        let filter = FileFilter {
            name_contains: Some("alpha"),
            limit: None,
            known_mtimes: None,
        };
        let found = discover(&tmp, filter);
        assert_eq!(found.len(), 1);
        assert!(found[0].0.ends_with("alpha.jsonl"));
        let filter2 = FileFilter {
            name_contains: None,
            limit: Some(1),
            known_mtimes: None,
        };
        assert_eq!(discover(&tmp, filter2).len(), 1);
        std::fs::remove_dir_all(&tmp).unwrap();
    }
}
