from __future__ import annotations

import os
import re
from collections import defaultdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import ClassVar, Literal

import orjson

from cc_sentiment.models import (
    AssistantMessage,
    BucketIndex,
    BucketKey,
    ConversationBucket,
    SessionId,
    ToolCall,
    TranscriptMessage,
    UserMessage,
)

from .backend import Backend

CLAUDE_PROJECTS_DIR = Path.home() / ".claude" / "projects"
BUCKET_MINUTES = 5
ASSISTANT_TRUNCATION = 1024
EPHEMERAL_ENTRYPOINTS: frozenset[str] = frozenset({"sdk-cli"})
MIN_USER_TURNS_PER_SESSION = 2

JUNK_USER_MESSAGE_RE = re.compile(
    r"<(?:system[_-](?:instruction|reminder)"
    r"|local-command-(?:stdout|caveat)"
    r"|command-(?:name|message|args)"
    r"|task-notification"
    r"|persisted-output"
    r"|output-file)\b"
    r"|Caveat: The messages below were generated by the user while running local commands\."
    r"|This session is being continued from a previous conversation that ran out of context\."
    r"|\[Request interrupted by user for tool use\]",
    re.IGNORECASE,
)


class TranscriptDiscovery:
    @staticmethod
    def find_transcripts() -> list[Path]:
        if not CLAUDE_PROJECTS_DIR.exists():
            return []
        return sorted(CLAUDE_PROJECTS_DIR.rglob("*.jsonl"))

    @staticmethod
    def transcript_mtime(path: Path) -> float:
        return path.stat().st_mtime

    @staticmethod
    def find_in(
        directory: Path,
        *,
        name_contains: str | None = None,
        limit: int | None = None,
        known_mtimes: dict[str, float] | None = None,
    ) -> list[tuple[Path, float]]:
        if not directory.exists():
            return []
        found = [
            (p, mtime)
            for p in directory.rglob("*.jsonl")
            if not name_contains or name_contains in p.name
            if (mtime := TranscriptDiscovery.stat_mtime(p)) is not None
            if known_mtimes is None
            or (prev := known_mtimes.get(str(p))) is None
            or prev < mtime
        ]
        found.sort(key=lambda e: e[0])
        return found[:limit] if limit is not None else found

    @staticmethod
    def stat_mtime(path: Path) -> float | None:
        try:
            return path.stat().st_mtime
        except OSError:
            return None


class ConversationBucketer:
    @staticmethod
    def align_to_bucket(ts: datetime) -> datetime:
        return ts.replace(
            minute=(ts.minute // BUCKET_MINUTES) * BUCKET_MINUTES,
            second=0,
            microsecond=0,
        )

    @classmethod
    def bucket_messages(
        cls, messages: list[TranscriptMessage]
    ) -> list[ConversationBucket]:
        by_session: dict[SessionId, list[TranscriptMessage]] = defaultdict(list)
        for msg in messages:
            by_session[msg.session_id].append(msg)

        buckets: list[ConversationBucket] = []
        for session_id, session_msgs in by_session.items():
            if sum(1 for m in session_msgs if isinstance(m, UserMessage)) < MIN_USER_TURNS_PER_SESSION:
                continue
            session_msgs.sort(key=lambda m: m.timestamp)
            session_start = cls.align_to_bucket(session_msgs[0].timestamp)

            grouped: dict[int, list[TranscriptMessage]] = defaultdict(list)
            for msg in session_msgs:
                idx = int(
                    (msg.timestamp - session_start) // timedelta(minutes=BUCKET_MINUTES)
                )
                grouped[idx].append(msg)

            for idx, bucket_msgs in sorted(grouped.items()):
                if not any(isinstance(m, UserMessage) for m in bucket_msgs):
                    continue
                if not any(isinstance(m, AssistantMessage) for m in bucket_msgs):
                    continue
                bucket_start = session_start + timedelta(minutes=BUCKET_MINUTES * idx)
                buckets.append(
                    ConversationBucket(
                        session_id=session_id,
                        bucket_index=BucketIndex(idx),
                        bucket_start=bucket_start,
                        messages=tuple(bucket_msgs),
                    )
                )

        return buckets


class PythonBackend:
    name: ClassVar[Literal["rust", "python"]] = "python"

    def parse_line(self, line: str) -> TranscriptMessage | None:
        try:
            data = orjson.loads(line)
        except orjson.JSONDecodeError:
            return None

        if data.get("entrypoint") in EPHEMERAL_ENTRYPOINTS:
            return None

        match data["type"]:
            case "queue-operation":
                return None
            case "user" if data.get("isSidechain"):
                return None
            case "user":
                match data["message"]["content"]:
                    case str(raw):
                        content = raw
                    case list(blocks) if (parts := [
                        b["text"] for b in blocks
                        if isinstance(b, dict) and b.get("type") == "text"
                    ]):
                        content = " ".join(parts)
                    case _:
                        return None
                if JUNK_USER_MESSAGE_RE.search(content):
                    return None
                content = content.strip()
                if not content:
                    return None
                return UserMessage(
                    content=content,
                    timestamp=datetime.fromisoformat(data["timestamp"]),
                    session_id=SessionId(data["sessionId"]),
                    uuid=data["uuid"],
                    tool_calls=(),
                    thinking_chars=0,
                    cc_version=data["version"],
                )
            case "assistant" if data["message"]["model"] == "<synthetic>":
                return None
            case "assistant":
                blocks = data["message"]["content"]
                text_blocks = [
                    b["text"] for b in blocks
                    if isinstance(b, dict) and b.get("type") == "text"
                ]
                tool_calls = tuple(
                    ToolCall(
                        name=b["name"],
                        file_path=b.get("input", {}).get("file_path"),
                    )
                    for b in blocks
                    if isinstance(b, dict) and b.get("type") == "tool_use"
                )
                thinking_chars = sum(
                    len(b.get("thinking", ""))
                    for b in blocks
                    if isinstance(b, dict) and b.get("type") == "thinking"
                )
                if not text_blocks and not tool_calls:
                    return None
                combined = " ".join(text_blocks)
                return AssistantMessage(
                    content=(
                        combined[:ASSISTANT_TRUNCATION] + "[...]"
                        if len(combined) > ASSISTANT_TRUNCATION
                        else combined
                    ),
                    timestamp=datetime.fromisoformat(data["timestamp"]),
                    session_id=SessionId(data["sessionId"]),
                    uuid=data["uuid"],
                    tool_calls=tool_calls,
                    thinking_chars=thinking_chars,
                    claude_model=data["message"]["model"],
                )
            case _:
                return None

    def parse_file(self, path: Path) -> list[TranscriptMessage]:
        return [
            msg
            for line in path.read_text().splitlines()
            if line.strip() and (msg := self.parse_line(line)) is not None
        ]

    def bucket_keys_for(self, path: Path) -> list[BucketKey]:
        by_session: dict[SessionId, list[tuple[datetime, bool]]] = defaultdict(list)
        for line in path.read_bytes().split(b"\n"):
            if not line.strip():
                continue
            try:
                data = orjson.loads(line)
            except orjson.JSONDecodeError:
                continue
            if data.get("entrypoint") in EPHEMERAL_ENTRYPOINTS:
                continue
            match data.get("type"):
                case "queue-operation":
                    continue
                case "user" if data.get("isSidechain"):
                    continue
                case "user":
                    match data["message"]["content"]:
                        case str(raw):
                            content = raw
                        case list(blocks) if (parts := [
                            b["text"] for b in blocks
                            if isinstance(b, dict) and b.get("type") == "text"
                        ]):
                            content = " ".join(parts)
                        case _:
                            continue
                    if JUNK_USER_MESSAGE_RE.search(content) or not content.strip():
                        continue
                    is_user = True
                case "assistant" if data["message"]["model"] == "<synthetic>":
                    continue
                case "assistant":
                    blocks = data["message"]["content"]
                    if not any(
                        isinstance(b, dict) and b.get("type") in ("text", "tool_use")
                        for b in blocks
                    ):
                        continue
                    is_user = False
                case _:
                    continue
            by_session[SessionId(data["sessionId"])].append(
                (datetime.fromisoformat(data["timestamp"]), is_user)
            )

        keys: list[BucketKey] = []
        for session_id, entries in by_session.items():
            if sum(1 for _, is_user in entries if is_user) < MIN_USER_TURNS_PER_SESSION:
                continue
            entries.sort(key=lambda e: e[0])
            session_start = ConversationBucketer.align_to_bucket(entries[0][0])
            grouped: dict[int, list[bool]] = defaultdict(list)
            for ts, is_user in entries:
                idx = int((ts - session_start) // timedelta(minutes=BUCKET_MINUTES))
                grouped[idx].append(is_user)
            keys.extend(
                BucketKey(session_id=session_id, bucket_index=BucketIndex(idx))
                for idx, flags in grouped.items()
                if any(flags) and not all(flags)
            )
        return keys

    def scan_bucket_keys(
        self,
        directory: Path,
        *,
        name_contains: str | None = None,
        limit: int | None = None,
        known_mtimes: dict[str, float] | None = None,
    ) -> list[tuple[Path, float, list[BucketKey]]]:
        return [
            (p, mtime, self.bucket_keys_for(p))
            for p, mtime in TranscriptDiscovery.find_in(
                directory,
                name_contains=name_contains,
                limit=limit,
                known_mtimes=known_mtimes,
            )
        ]


class TranscriptParser:
    BACKEND: ClassVar[Backend | None] = None

    @classmethod
    def backend(cls) -> Backend:
        if cls.BACKEND is None:
            cls.BACKEND = cls.resolve_backend()
        return cls.BACKEND

    @classmethod
    def resolve_backend(cls) -> Backend:
        if os.environ.get("CC_SENTIMENT_DISABLE_RUST"):
            return PythonBackend()
        try:
            from .rust import RustBackend
        except ImportError:
            return PythonBackend()
        return RustBackend()

    @classmethod
    def backend_name(cls) -> Literal["rust", "python"]:
        return cls.backend().name

    @classmethod
    def parse_line(cls, line: str) -> TranscriptMessage | None:
        return cls.backend().parse_line(line)

    @classmethod
    def parse_file(cls, path: Path) -> list[TranscriptMessage]:
        return cls.backend().parse_file(path)

    @classmethod
    def bucket_keys_for(cls, path: Path) -> list[BucketKey]:
        return cls.backend().bucket_keys_for(path)

    @classmethod
    def scan_bucket_keys(
        cls,
        directory: Path,
        *,
        name_contains: str | None = None,
        limit: int | None = None,
        known_mtimes: dict[str, float] | None = None,
    ) -> list[tuple[Path, float, list[BucketKey]]]:
        return cls.backend().scan_bucket_keys(
            directory,
            name_contains=name_contains,
            limit=limit,
            known_mtimes=known_mtimes,
        )


__all__ = [
    "ASSISTANT_TRUNCATION",
    "BUCKET_MINUTES",
    "CLAUDE_PROJECTS_DIR",
    "ConversationBucketer",
    "EPHEMERAL_ENTRYPOINTS",
    "JUNK_USER_MESSAGE_RE",
    "MIN_USER_TURNS_PER_SESSION",
    "PythonBackend",
    "TranscriptDiscovery",
    "TranscriptParser",
]
